CREATE DATABASE IF NOT EXISTS sbd
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS public."package"
(
    packageid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    status boolean NOT NULL DEFAULT false,
    date timestamp with time zone NOT NULL DEFAULT now(),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT package_pkey PRIMARY KEY (packageid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."package"
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.users
(
    userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (userid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;